# Generated by Django 4.2.7 on 2023-11-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categortType',
            new_name='categoryType',
        ),
    ]
